version: '{build}'
clone_depth: 1

platform: x86

skip_tags: true

environment:
  GOROOT: c:\go110-x86
  GOVERSION: 1.10

install:
- cmd: set GOPATH=%BuildFolder%
- cmd: PATH C:\msys64\mingw32\bin;C:\msys64\bin;C:\msys64\usr\bin;%GOROOT%\bin;%GOPATH%\bin
- cmd: go env
- cmd: go version

build_script:
- cmd: env APPVEYOR_BUILD_NUMBER="$(APPVEYOR_BUILD_NUMBER)" bash -ex ./appveyor/build.sh

artifacts:
- path: build/artifacts/test-build-$(APPVEYOR_BUILD_NUMBER)-win32.zip
  name: tarball
